### ISSUE TITLE
Compares badly with PlasmaConfigSaver

### ISSUE THREAD

**Issue by ben2talk** [selplacei/konfsave#3]
I am trying to manage profiles. Right now I have three.

1. Card - light creamy, light latte with contrasting text in Event Calendar. Also matching default Konsole profile needs switching, and Dolphin terminal also.

2. Gruv is a grey-green dark profile for comfort, with matching colours in latte/konsole profile etc.

3. Nordic - (less dark) cold colours theme.

I was testing switching this morning, using shortcuts for restarting plasma and restarting kwin without logging out.

konsave fails to switch terminal (konsole and dolphin) and requires manual latte restart, and is vastly inferior to the plasmaconfigsaver.

konfsave fails to switch terminal (konsole) and fails to update the event calendar colours in latte.

As I say, PlasmaConfigSaver usually succeeds, though I sometimes need to do kwin restart and plasmashell restart again.

It is obviously interesting that you will have a config file. I would like to add a new default profile save path (i.e. default to ~/Dropbox/.config) and also add qbittorrent settings, as the dark icon works with profile 1, light icon with 3, and plasma icon with 2.

**Comment by selplacei** [comment]
You can add Konsole and Dolphin settings to the list of files to save by default; specifically, you would open `~/.config/konfsave/konfsave.ini` and change `save-list=kde` to `save-list=kde,konsole,dolphin`. Additionally, if you want to change shell settings as well, add `shells` (bash and zsh are there by default, you can add others too - see the GitHub wiki for more info on how to adjust the config).

As for the profile path, you can either export your profile using `konfsave archive` or change the data location in `constants.py`. I'm currently planning to move this setting (and others) to the config file as well.

Latte is supposed to be restarted by Konfsave - if it doesn't, that's definitely a bug. Are you on the latest version? What is the output if you change log-level to DEBUG?

**Comment by selplacei** [comment]
Since 0.4.0, the profile home path and a couple other things are configurable.

**Comment by selplacei** [comment]
Assuming this is safe to close.
