### ISSUE TITLE
Profile names cannot contain dashes or underscores

### ISSUE THREAD

**Issue by silvernode** [selplacei/konfsave#8]
Not much else to say other than it should be easily reproducible. No need to really explain how to achieve this as it should be self explanatory.

**Comment by selplacei** [comment]
It should be possible to use underscores - I just tried and it works.

As for other characters, I never thought that it would be a desired feature. Should be a simple change, will implement soon.

**Comment by selplacei** [comment]
Should be fixed in 0.4.2.

**Comment by silvernode** [comment]
My mistake about the underscore part. I swear I tried it and it did not work but I must have not after all. As for dashes, I wanted to name my profile backup "themeName-hostname" to help me identify which theme and machine the profile came from.

Thanks for the quick response and the great project. You are a better project maintainer than me. 

Cheers
